;===========================================================================
;                               Graphics.inc
;---------------------------------------------------------------------------
; Assembly x86 library
;
;
; Author: Ahmed Hussein
; Created: 
;===========================================================================



;-------------------- Includes --------------------
include AsmLib\Graphics\Gfx.asm
include AsmLib\Graphics\Draw.asm
include AsmLib\Graphics\Print.asm
include AsmLib\Graphics\Anim.asm
include AsmLib\Graphics\Sound.asm