;===========================================================================
; 								  Util.inc
;---------------------------------------------------------------------------
; Assembly x86 library
;
;
; Author: Ahmed Hussein
; Created: 
;===========================================================================



;-------------------- Includes --------------------
include AsmLib\Util\Util.asm
include AsmLib\Util\FileMang.asm
include AsmLib\Util\Heap.asm
include AsmLib\Util\KeyMang.asm
include AsmLib\Util\Serial.asm
include AsmLib\Util\Math.asm
include AsmLib\Util\Time.asm