;===========================================================================
; 								Utilities.inc
;---------------------------------------------------------------------------
; Assembly x86 library
;
;
; Author: Ahmed Hussein
; Created: 
;===========================================================================


;-------------------- Definitions --------------------
TRUE        EQU     1
FALSE       EQU     0
NULL        EQU     0


;-------------------- Includes --------------------
include "Utilities\Utilities.asm"
include "Utilities\FileManagement.asm"
include "Utilities\MemoryManagement.asm"
include "Utilities\KeysScanCodeMap.asm"
include "Utilities\KeyboardManagement.asm"
include "Utilities\SerialCommunication.asm"
include "Utilities\Math.asm"
include "Utilities\Time.asm"